services:
  express:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_URL: ${URI_MONGO_DB}
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example